/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as AuthLayoutSingUpRouteImport } from './routes/_auth/_layout.sing-up'
import { Route as AuthLayoutSingInRouteImport } from './routes/_auth/_layout.sing-in'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutSingUpRoute = AuthLayoutSingUpRouteImport.update({
  id: '/sing-up',
  path: '/sing-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSingInRoute = AuthLayoutSingInRouteImport.update({
  id: '/sing-in',
  path: '/sing-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sing-in': typeof AuthLayoutSingInRoute
  '/sing-up': typeof AuthLayoutSingUpRoute
}
export interface FileRoutesByTo {
  '/sing-in': typeof AuthLayoutSingInRoute
  '/sing-up': typeof AuthLayoutSingUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/_layout/sing-in': typeof AuthLayoutSingInRoute
  '/_auth/_layout/sing-up': typeof AuthLayoutSingUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sing-in' | '/sing-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/sing-in' | '/sing-up'
  id:
    | '__root__'
    | '/_auth/_layout'
    | '/_auth/_layout/sing-in'
    | '/_auth/_layout/sing-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout/sing-up': {
      id: '/_auth/_layout/sing-up'
      path: '/sing-up'
      fullPath: '/sing-up'
      preLoaderRoute: typeof AuthLayoutSingUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/sing-in': {
      id: '/_auth/_layout/sing-in'
      path: '/sing-in'
      fullPath: '/sing-in'
      preLoaderRoute: typeof AuthLayoutSingInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutSingInRoute: typeof AuthLayoutSingInRoute
  AuthLayoutSingUpRoute: typeof AuthLayoutSingUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutSingInRoute: AuthLayoutSingInRoute,
  AuthLayoutSingUpRoute: AuthLayoutSingUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
