/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeLayoutRouteImport } from './routes/_home/_layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as HomeLayoutUsersRouteImport } from './routes/_home/_layout.users'
import { Route as HomeLayoutOrganizationRouteImport } from './routes/_home/_layout.organization'
import { Route as HomeLayoutHomeRouteImport } from './routes/_home/_layout.home'
import { Route as AuthLayoutSignUpRouteImport } from './routes/_auth/_layout.sign-up'
import { Route as AuthLayoutSignInRouteImport } from './routes/_auth/_layout.sign-in'

const HomeLayoutRoute = HomeLayoutRouteImport.update({
  id: '/_home/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutUsersRoute = HomeLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const HomeLayoutOrganizationRoute = HomeLayoutOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const HomeLayoutHomeRoute = HomeLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const AuthLayoutSignUpRoute = AuthLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSignInRoute = AuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthLayoutSignInRoute
  '/sign-up': typeof AuthLayoutSignUpRoute
  '/home': typeof HomeLayoutHomeRoute
  '/organization': typeof HomeLayoutOrganizationRoute
  '/users': typeof HomeLayoutUsersRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthLayoutSignInRoute
  '/sign-up': typeof AuthLayoutSignUpRoute
  '/home': typeof HomeLayoutHomeRoute
  '/organization': typeof HomeLayoutOrganizationRoute
  '/users': typeof HomeLayoutUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_home/_layout': typeof HomeLayoutRouteWithChildren
  '/_auth/_layout/sign-in': typeof AuthLayoutSignInRoute
  '/_auth/_layout/sign-up': typeof AuthLayoutSignUpRoute
  '/_home/_layout/home': typeof HomeLayoutHomeRoute
  '/_home/_layout/organization': typeof HomeLayoutOrganizationRoute
  '/_home/_layout/users': typeof HomeLayoutUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/sign-up' | '/home' | '/organization' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/sign-up' | '/home' | '/organization' | '/users'
  id:
    | '__root__'
    | '/_auth/_layout'
    | '/_home/_layout'
    | '/_auth/_layout/sign-in'
    | '/_auth/_layout/sign-up'
    | '/_home/_layout/home'
    | '/_home/_layout/organization'
    | '/_home/_layout/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home/_layout': {
      id: '/_home/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/_layout/users': {
      id: '/_home/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof HomeLayoutUsersRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_home/_layout/organization': {
      id: '/_home/_layout/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof HomeLayoutOrganizationRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_home/_layout/home': {
      id: '/_home/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLayoutHomeRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_auth/_layout/sign-up': {
      id: '/_auth/_layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthLayoutSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/sign-in': {
      id: '/_auth/_layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
  AuthLayoutSignUpRoute: typeof AuthLayoutSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
  AuthLayoutSignUpRoute: AuthLayoutSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface HomeLayoutRouteChildren {
  HomeLayoutHomeRoute: typeof HomeLayoutHomeRoute
  HomeLayoutOrganizationRoute: typeof HomeLayoutOrganizationRoute
  HomeLayoutUsersRoute: typeof HomeLayoutUsersRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutHomeRoute: HomeLayoutHomeRoute,
  HomeLayoutOrganizationRoute: HomeLayoutOrganizationRoute,
  HomeLayoutUsersRoute: HomeLayoutUsersRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
